--- # AWS EC2 Instance Communication Shell Command Example
- hosts: aws
  remote_user: ubuntu
  become_method: sudo
  gather_facts: true
  connection: ssh
  tasks:
  - name: install apache2
      apt: name=apache2 update_cache=yes state=latest
  - name: Display the result in JSON format
    debug: var=result
